# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go test -v ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{ .Version }} -X main.Commit={{ .Commit }} -X main.BuildDate={{ .CommitDate }}
    main: ./cmd/main.go

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  # build latest and specific tag version images
  # https://goreleaser.com/cookbooks/multi-platform-docker-images/#other-things-to-pay-attention-to
  - image_templates:
      # https://goreleaser.com/cookbooks/override-image-name/
      - "ghcr.io/linode-obs/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/linode-obs/{{ .ProjectName }}:{{ .Tag }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.title={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source=https://github.linode.com/linode-obs/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.description='o11y platform canary'"
    - "--label=org.opencontainers.image.licenses=MIT"
    - "--platform=linux/amd64"
    dockerfile: "Dockerfile"
  - image_templates:
      - "ghcr.io/linode-obs/{{ .ProjectName }}:{{ .Tag }}-linux-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.title={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source=https://github.linode.com/linode-obs/{{ .ProjectName }}"
    - "--label=org.opencontainers.image.description='o11y platform canary'"
    - "--label=org.opencontainers.image.licenses=MIT"
    - "--platform=linux/arm64"
    dockerfile: "Dockerfile"
