# https://goreleaser.com/errors/docker-build/#do
ARG ARCH="amd64"
ARG OS="linux"
FROM golang:alpine3.21 AS builderimage
LABEL maintainer="Akamai SRE Observability Team <support@linode.com>"
COPY o11y-canary /app/o11y-canary
WORKDIR /app
EXPOSE 8080
USER nobody
ENTRYPOINT ["./o11y-canary"]
