services:
  o11y-canary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./test/config.yaml:/config.yaml
    command:
      - -log.level=debug
      - -config=/config.yaml
      - -tracing.endpoint=otel-collector:4317
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    ports:
      - 4317:4317
      - 4318:4318
      - 8888:8888
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command: ["--config=file:/etc/otel-collector.yaml"]
  vm-singleton:
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - "8428:8428"
    volumes:
      - ./vm-scrape.yaml:/scrape.yaml
    command:
      - '-loggerLevel=INFO'
      - '-promscrape.config=scrape.yaml'
      - '-selfScrapeInterval=10s'
  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    # Override entrypoint if you want use options
    entrypoint: ["/otel-tui", "--grpc", "4320", "--enable-prom", "--prom-target", "o11y-canary:8080"]