apiVersion: v1
kind: Service
metadata:
  name: o11y-canary
  labels:
    app: o11y-canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: o11y-canary
