name: Automated venom integration tests

on:
  push:
    tags:
        - v*
    branches: [main]
  workflow_call:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download venom
        run: curl https://github.com/ovh/venom/releases/download/v1.2.0/venom.linux-amd64 -L -o /usr/local/bin/venom && chmod +x /usr/local/bin/venom

      - name: Run test
        run: sudo venom run tests.yml

      - name: Output venom log
        if: always()
        run: cat venom.log
